---
title: "Flextable formatting"
author: "Laura Webster"
date: "03/12/2019"
output:
  word_document:
    toc: yes
  pdf_document:
    number_sections: no
    toc: yes
---

```{r setup, include = FALSE, results = 'hide', warning = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.pos = 'H'
)

#library(readxl)
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(flextable))
suppressPackageStartupMessages(library(huxtable))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(officer))
suppressPackageStartupMessages(library(kableExtra))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(cowplot))


```

> this is how to print a flextable in an R Markdown document
    

```{r}
data <- fread("Input/dist_effects_yll.csv", header = TRUE)
data <- flextable(data)
data <- merge_v(data, j = c("Sex"))
data <- colformat_int(data, j = c("2035", "2091"),
      big.mark = ",", na_str = "", prefix = "", suffix = "")

data <- autofit(data)


data <- theme_vanilla(data)
data
#data <- fix_border_issues(data)
#set_caption(data, "caption")


```













